### ISSUE TITLE
Is there a way to make time optional?

### ISSUE THREAD

**Issue by kjnilsson** [amir/raidman#6] opened 2015-01-23 11:48 UTC
This bit of code here suggests there is not but I  don't really know go very well. 

https://github.com/amir/raidman/blob/master/proto/proto.pb.go#L32

Thanks.

**Comment by amir** [comment] 2015-01-25 13:33
Hi,

On Events, or Queries? While sending Events, all events are optional and you can omit any of the raidman.Event{} fields. But I just realized that the clojure client automatically sets Event time if you don't provide it, while raidman passes empty value. Is that the behaviour you want to be implemented?

**Comment by amir** [comment] 2015-03-28 10:00
I just pushed a fix concerning reflection regression in go1.4. I'm not sure if it has anything to do with the problem you had, but thought updating this issue anyway.

**Comment by amir** [comment] 2015-04-10 09:10
Closing this issue due to inactivity. Feel free to reopen.

**Closed by amir** 2015-04-10 09:10 UTC
